/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Jul 20 16:42:52 2017
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define Joint_0_id 1
#define Joint_1_id 2
#define Joint_2_id 3
#define Joint_3_id 4
#define Joint_4_id 5
#define Joint_5_id 6
#define Joint_6_id 7
#define Joint_9_id 8
#define Joint_10_id 9
#define Joint_12_id 10
#define Joint_17_id 11
#define Joint_18_id 12
#define Joint_14_id 13
#define Joint_21_id 14
#define Joint_22_id 15
#define Joint_13_id 16
#define Joint_20_id 17


// body

#define torso_bott_id 6
#define torso_up_id 7
#define shoulder_R_2_id 8
#define arm_R_id 9
#define elbow_R_id 10
#define shoulder_L_2_id 11
#define arm_L_id 12
#define elbow_L_id 13
#define nek_id 14
#define head_id 15
#define Right_wheel_id 16
#define Left_wheel_id 17


// point

//#define torso_bott_origin_id 1
#define torso_bott_Point_0_id 2
#define torso_bott_Point_1_id 3
#define torso_bott_Point_2_id 4
//#define torso_up_origin_id 5
#define torso_up_Point_0_id 6
#define torso_up_Point_1_id 7
#define torso_up_Point_2_id 8
//#define shoulder_R_2_origin_id 9
//#define arm_R_origin_id 10
#define arm_R_Point_0_id 11
//#define elbow_R_origin_id 12
//#define shoulder_L_2_origin_id 13
//#define arm_L_origin_id 14
#define arm_L_Point_0_id 15
//#define elbow_L_origin_id 16
//#define nek_origin_id 17
//#define Right_wheel_origin_id 18
//#define Left_wheel_origin_id 19


// sensor

#define Sensor_torso_bott_id 1
#define Sensor_torso_up_id 2
#define Sensor_shoulder_R_2_id 3
#define Sensor_arm_r_id 4
#define Sensor_elbow_R_id 5
#define Sensor_shoulder_L_2_id 6
#define Sensor_arm_L_id 7
#define Sensor_elbow_L_id 8
#define Sensor_0_id 9
#define Sensor_right_wheel_id 10
#define Sensor_left_wheel_id 11


// extforce

#define ExtForce_right_wheel_id 1
#define ExtForce_left_wheel_id 2


// links



// Rods



// ============================================================ //

# endif
