/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Jul 20 16:42:52 2017
 * --------------------------------------------------------
 *
 */
#ifndef user_IO_h
#define user_IO_h


#include "mbs_user_interface.h"
// ============================================================ //


struct UserIO 
{
    double motorTorque_left;
    double motorTorque_right;
};

// ============================================================ //
 
# endif
