/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Jul 20 16:42:52 2017
 * --------------------------------------------------------
 *
 */
#include <stdlib.h>
#include "user_IO.h"

// ============================================================ //


UserIO* mbs_new_user_IO(UserIoInfo* ioInfo) 
{
    UserIO *uio;
    uio = (UserIO*) malloc(sizeof(UserIO));

    // init motorTorque_left
    ioInfo->ptr_in[0] = &uio->motorTorque_left;

    // init motorTorque_right
    ioInfo->ptr_in[1] = &uio->motorTorque_right;

    return uio;
}



void mbs_delete_user_IO(UserIO *uio)
{

    free(uio);
}

// ============================================================ //
 
