/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Jul 20 16:42:52 2017
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 2.4
#define M_7 1
#define M_8 0.6
#define M_9 0.35
#define M_10 0.3
#define M_11 0.6
#define M_12 0.35
#define M_13 0.3
#define M_14 0.6
#define M_15 0.6
#define M_16 0.38
#define M_17 0.38

// center of mass
#define L_1_6 -0.0015
#define L_2_6 0.001
#define L_1_8 0.0013
#define L_2_8 0.0031
#define L_1_9 0.0019
#define L_3_9 0.012
#define L_2_10 0.0027
#define L_3_10 0.0048
#define L_1_11 0.0013
#define L_2_11 -0.0031
#define L_1_12 0.0019
#define L_3_12 0.012
#define L_2_13 -0.0027
#define L_3_13 0.0048

// inertia
#define IN_1_6 0.0695
#define IN_5_6 0.0377
#define IN_9_6 0.033
#define IN_1_7 0.1
#define IN_5_7 0.1
#define IN_9_7 0.1
#define IN_1_8 0.000223
#define IN_5_8 0.000198
#define IN_9_8 0.000242
#define IN_1_9 0.000445
#define IN_5_9 0.000508
#define IN_9_9 0.000208
#define IN_1_10 0.000186
#define IN_5_10 0.000162
#define IN_9_10 0.000155
#define IN_1_11 0.000223
#define IN_5_11 0.000198
#define IN_9_11 0.000442
#define IN_1_12 0.000445
#define IN_5_12 0.000508
#define IN_9_12 0.000208
#define IN_1_13 0.000186
#define IN_5_13 0.000162
#define IN_9_13 0.000155
#define IN_1_14 0.000223
#define IN_5_14 0.000198
#define IN_9_14 0.000442
#define IN_1_15 0.000223
#define IN_5_15 0.000198
#define IN_9_15 1e-05
#define IN_1_16 0.0012
#define IN_5_16 0.0024
#define IN_9_16 0.0012
#define IN_1_17 0.0012
#define IN_5_17 0.0024
#define IN_9_17 0.0012

// body point
#define DPT_3_2 0.45
#define DPT_2_3 -0.2285
#define DPT_2_4 0.2285
#define DPT_2_6 -0.164
#define DPT_2_7 0.164
#define DPT_3_8 0.1
#define DPT_3_11 -0.078
#define DPT_3_15 -0.078

// ============================================================ //

# endif
